version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: israel_flights
    env_file:
      - .env
  backend:
    build: ./backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  fetcher:
    build: ./backend
    command: ["python", "/app/fetch_flights_periodically.py"]
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    command: ["streamlit", "run", "/app/frontend.py"]
    environment:
      BASE_URL: http://backend:8000
    volumes:
      - ./frontend:/app
    ports:
      - 8501:8501
    depends_on:
      - backend

